name: Node CI

push:
  branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.9.1]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and publish
      run: |
        npm install
        npm run build --if-present
        npm run predeploy
        npm run deploy
      env:
        CI: true
        CD: true
